### ISSUE TITLE
Issues Format

### ISSUE THREAD

**Issue by Nathan13768609** [ajahiri/M01-Studio2A-P3#3]
Briefly explain the problem.

GitHub Branch:

Steps to Recreate Error:

1. 
2. 
3. 

More details and symptoms of the bug (including possible causes and/or possible solutions if any)

Titled screen shots of symptoms, error messages or relevant code.

**Comment by Nathan13768609** [comment]
----When fix is found----
Describe the cause of the bug

Descibe what was done to fix the bug

Any relevent screen shots (titled)

**Comment by younesDev00** [comment]
this issue has been solved
